# Generated by Django 5.1.15 on 2026-03-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_points_quizattempt_total_points_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_points_earned',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_points_possible',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
