# Generated by Django 5.1.15 on 2026-04-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'Simple'), ('mid', 'Medium'), ('hard', 'Hard')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='raw_score',
            field=models.FloatField(default=0.0),
        ),
    ]
