# Generated by Django 5.1.15 on 2026-04-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_difficulty_quizattempt_raw_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='raw_score',
            new_name='total_marks',
        ),
    ]
