# Generated by Django 5.1.15 on 2026-04-04 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_attemptanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Allowed time for students to complete the quiz (minutes).'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Quiz becomes accessible to students at this datetime. Leave blank for immediate access when published.', null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_level', models.CharField(choices=[('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('admission', 'Admission')], max_length=20)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'ordering': ['class_level', 'name'],
                'unique_together': {('name', 'class_level')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.subject'),
        ),
    ]
